DB_SERVER = ""
DB_USER = ""
DB_PASSWD = ""
DB_NAME = ""

TABLE_BADGE = "badge"
TABLE_CATEGORY = "category"
TABLE_DISCOUNT = "discount"
TABLE_DISCOUNT_USER = "discount_user"
TABLE_MESSAGE = "message"
TABLE_QUESTION = "question"
TABLE_QUESTION_CATEGORY = "question_category"
TABLE_SELLER = "seller"
TABLE_SHOP = "shop"
TABLE_SHOP_BADGE = "shop_badge"
TABLE_USER = "user"
TABLE_USER_QUESTION = "user_question"

SALT = ""